version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: my-rabbit
    ports:
      - 5672:5672
  orig:
    build:
      context: ./ORIG
      dockerfile: Dockerfile
    expose: [8001]
    command: npm start
  imed:
    build:
      context: ./IMED
      dockerfile: Dockerfile
    expose: [8002]
    command: npm start
  obser:
    build:
      context: ./OBSE
      dockerfile: Dockerfile
    volumes:
      - ./data
    expose: [8003]
    command: npm start
  httpserv:
    build:
      context: ./HTTPSERV
      dockerfile: Dockerfile
    volumes_from:
      - obser
    ports:
      - 8080:8080
    command: npm start
